name: Deploy index.html to EC2 (Nginx)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: verify file exists
        run: |
          ls -l
          cat index.html  

      - name: Copy to file
        uses: appleboy/scp-action@v0.1.7
        with: 
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "index.html"
          target: "/home/ec2-user/"
          

      - name: move file to nginx dir
        uses: appleboy/ssh-action@v0.1.6
        with: 
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
             sudo mv /home/ec2-user/index.html /usr/share/nginx/html/index.html